### PR TITLE
Updates for FIRRTL 3.2.0

### LINKED ISSUE #4: Add Indentation Support for Memories
Memories don't currently work for indentation. Add support for this.

### PR DESCRIPTION
**Pull request by seldridge**
This includes miscellaneous, accumulated updates to FIRRTL syntax since the 0.3.0 release. This includes everything in the [3.1.0 Release](https://github.com/chipsalliance/firrtl-spec/releases/tag/v3.1.0) and the groups feature expected to land in 3.2.0. Indentation support is added/fixed for memories, groups, and comments.

Fixes #4.

@rbertran: Do you happen to have access to approve and merge PRs on this repo?

### CODE REVIEW

**Comment by rbertran** [comment]
I do not have access :( ...  I might have missed it when I requested access to all your IBM public projects last time.  I'll request access in the following days and accept this PR.  Thank you! ;)

**Comment by seldridge** [comment]
👋 Thanks for looking into it @rbertran! As the FIRRTL spec continues to evolve, I'll pester you for some more reviews/rubber stamps. 😉

**Comment by rbertran** [comment]
Merged!

**Comment by seldridge** [comment]
Thanks, @rbertran!

**Pull request merged**
